spring:
  application:
    name: inventory-service

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

    consumer:
      group-id: inventory-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        # ✅ CRITICAL FIX
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

        # Trust packages (for deserialization)
        spring.json.trusted.packages: "com.srotip.events"

        # Ignore producer class type
        spring.json.use.type.headers: false

        # Map topics → local DTOs
        spring.json.value.default.type: com.srotip.events.ProductCreatedEvent

server:
  port: ${INVENTORY_SERVICE_PORT}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka